/*
    The original program was an example of simple if-else usage.
    I've modified it so that it utilizes loops (for easier testing purposes)
    and added a try-catch block to detect when the user
    has entered invalid value or data type for the integer grade
*/
#include <iostream>
#include <stdexcept> // ! used for std::exceptions

int main()
{
    char answer;
    do
    {
        int grade;

        while (true)
        {

            try
            {
                std::cout << "\nEnter a grade (0-100): ";

                std::cin >> grade;

                if (std::cin.fail())
                {
                    std::cin.clear();             // removes any error flags generated by cin
                    std::cin.ignore(10000, '\n'); // discards any characters that are in the input buffer
                    throw std::invalid_argument("Invalid Input: not a number");
                }

                if (grade < 0 || grade > 100)
                    throw std::out_of_range("Invalid Input: grade is out of range.");

                break;
            }

            catch (const std::invalid_argument &e)
            {
                std::cout << e.what() << '\n';
            }

            catch (const std::out_of_range &e)
            {
                std::cout << e.what() << '\n';
            }
        }

        if (grade >= 70)
            std::cout << "You passed!\n";
        else
            std::cout << "You failed!\n";

        std::cout << "\nDo you want to continue (y/n): ";
        std::cin >> answer;

    } while (answer != 'n');

    std::cout << "Okay bye.\n";
    return 0;
}